# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

development:
  adapter: postgresql
  host: localhost
  username: dean105
  password: parreno
  database: sample_app3_dev
  encoding: UTF8

test:
  adapter: postgresql
  host: localhost
  username: dean105
  password: parreno
  database: sample_app3_test   # or whatever the name is
  encoding: UTF8
production:
  adapter: postgresql
  host: localhost
  username: dean105
  password: parreno
  database: sample_app3_prod  # or whatever the name is
  encoding: UTF8
